name: roofing-project-2
services:
- name: web
  source_dir: /
  github:
    repo: bbarnes4318/roofing-project-2
    branch: bubbles-sep29
  build_command: npm install && npm run build && mkdir -p server/public && cp -r build/* server/public/
  run_command: NODE_ENV=production node server/server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: REACT_APP_API_URL
    value: "https://goldfish-app-4yuma.ondigitalocean.app/api"
  - key: REACT_APP_SOCKET_URL
    value: "https://goldfish-app-4yuma.ondigitalocean.app"
  - key: REACT_APP_GOOGLE_MAPS_API_KEY
    value: "AIzaSyBL-BzpAUPd-Deu8LndaoQO367iokdlehM"
  http_port: 8080
  routes:
  - path: /api
  - path: /