name: roofing-project-2
services:
- name: web
  source_dir: /
  github:
    repo: bbarnes4318/roofing-project-2
    branch: master
  build_command: npm install && npm run build && cd server && npm install
  run_command: cd server && NODE_ENV=production node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  http_port: 8080
  routes:
  - path: /