name: Server CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Generate Prisma Client
        working-directory: server
        run: npx prisma generate

      - name: Run tests
        working-directory: server
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/db
          JWT_SECRET: test
        run: npm test --silent